name: 'Hello World JS Action'
description: 'Great someone and record the time'

on:
  workflow_dispatch:  # Manually triggered by a user
  
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'

outputs:
  time:
    description: 'The time we greeted you'

runs:
  using: 'node16'
  main: 'index.js'
