name: 'Hello World JS Action'
description: 'Great someone and record the time'

on:
  workflow_dispatch:  # Manually triggered by a user
    inputs:
      who-to-greet:
        description: 'Who to greet'
        required: true
        default: 'World'

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Greet and record time
        id: greet_time
        run: |
          node index.js "${{ github.event.inputs.who-to-greet }}"
        env:
          GREETING_TIME: ${{ steps.greet_time.outputs.time }}

    outputs:
      time: ${{ steps.greet_time.outputs.time }}
